import { ShieldCheck } from "lucide-react";

export function AiDisclaimer({ className = "" }: { className?: string }) {
  return (
    <div
      className={`flex items-start gap-3 rounded-xl border border-border/60 bg-muted/40 p-4 text-sm text-muted-foreground ${className}`}
    >
      <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
      <p className="min-w-0 leading-relaxed">
        <span className="font-medium text-foreground">Responsible AI:</span> safe-SPACE AI offers
        supportive suggestions only. Responses are generated by an AI model, may be inaccurate, and
        are not medical, legal, or financial advice. Nothing you write here is used to train models,
        and your tasks stay on this device.
      </p>
    </div>
  );
}
